os:       linux
dist:     bionic
language: shell
services: docker
env:      TRAVIS_TAG="x86_64" REPO_NAME="${TRAVIS_REPO_SLUG#*/}" DEPLOY_HOME="aurdeploy:/home/aurbuild"

notifications:
  email: false

jobs:
  include:
  - stage: build docker image
    script:
    - if [[ ! -d "config" ]]; then exit 1; fi
    - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
    - docker build -t ${REPO_NAME} .
    - docker images
    - docker tag ${REPO_NAME} ${TRAVIS_REPO_SLUG}
    - docker push ${TRAVIS_REPO_SLUG}

  - stage: build packages
    before_install:
    - docker run --rm --name ${REPO_NAME} -dt ${REPO_NAME} bash

    install:
    - bash ${TRAVIS_BUILD_DIR}/.travis/install.sh

    script:
    - bash ${TRAVIS_BUILD_DIR}/.travis/script.sh

    before_deploy:
    - docker cp ${DEPLOY_HOME}/pkg ${TRAVIS_TAG}

    deploy:
    - provider: releases
      token: ${GITHUB_TOKEN}
      file_glob: true
      file: ${TRAVIS_TAG}/*{db,files,gz,xz}
      overwrite: true
      skip_cleanup: true
      on:
        branch: ${DEPLOY_BRANCH}
        condition: ${DEPLOY_GITHUB} != 0

    - provider: script
      script: docker exec ${REPO_NAME} bash sftp.sh
              ${SFTP_USER} ${SFTP_HOST} ${SFTP_PASS} ${SFTP_DIR} ${TRAVIS_TAG}
      skip_cleanup: true
      on:
        branch: ${DEPLOY_BRANCH}
        condition: ${DEPLOY_SFTP} == 1
